import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2{
            font-size: 38px;
          }
          h3{
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>HUNTING CODER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        HUNTING CODER
        </h1>

        <p className={styles.description}>
          A Blog for hunting coders by hunting coder
        </p>

        <div className={styles.blogSection}>
          <div className={styles.blogHead}>
            <h2>Popular Blogs</h2>
          </div>
          <div className={styles.blogs}>
            <div className={styles.blog}>
              <h3>How to learn JavaScript in 2022?</h3>
              <p>JavaScript is the language used to design logic for the web.</p>
            </div>
            <div className={styles.blog}>
              <h3>How to learn JavaScript in 2022?</h3>
              <p>JavaScript is the language used to design logic for the web.</p>
            </div>
            <div className={styles.blog}>
              <h3>How to learn JavaScript in 2022?</h3>
              <p>JavaScript is the language used to design logic for the web.</p>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
